### ISSUE TITLE
Allow asking acorn to parse in module mode

### ISSUE THREAD

**Issue by mappu** [AdeonMaster/jsx-vanilla#3]
Hi, thanks for these projects, they are an excellent direction for javascript.

My webpack pipeline runs { Typescript modules tsx -> Javascript ES6 modules JSX preserved -> jsx-vanilla Javascript ES6 modules } on multiple files, and then does a single Babel pass ES6->ES5 at the end.

This is a little bit uncommon for webpack, often people use babel-loader on a per-file basis, but doing it globally results in better overall compression.

However as a result, jsx-vanilla sees an ES6 module file instead of an ES6 script file.

It produces this error from acorn:

```
Module build failed (from ./node_modules/jsx-vanilla-loader/index.js):
SyntaxError: 'import' and 'export' may appear only with 'sourceType: module' (2:0)
    at Object.pp$4.raise (...\node_modules\jsx-vanilla\node_modules\acorn\dist\acorn.js:2927:15)
    at Object.pp$1.parseStatement (...\node_modules\jsx-vanilla\node_modules\acorn\dist\acorn.js:870:18)
    at Object.pp$1.parseTopLevel (...\node_modules\jsx-vanilla\node_modules\acorn\dist\acorn.js:755:23)
    at Object.parse (...\node_modules\jsx-vanilla\node_modules\acorn\dist\acorn.js:555:17)
    at Function.parse (...\node_modules\jsx-vanilla\node_modules\acorn\dist\acorn.js:578:37)
    at findJSXNode (...\node_modules\jsx-vanilla\lib\find-jsx-node.js:17:34)
    at preprocess (...\node_modules\jsx-vanilla\lib\process.js:32:46)
    at Object.module.exports (...\node_modules\jsx-vanilla-loader\index.js:6:9)
```

- Is it possible to please expose acorn's settings - specifically the "sourceType": "module" field - up through jsx-vanilla, and (ideally...) also up through jsx-vanilla-loader?

I believe this would help me solve my issue,

**Comment by AdeonMaster** [comment]
@mappu could you please provide a minimal workable example of your webpack pipeline? Ideally would be to use https://codesandbox.io for it

**Comment by cangokdayi** [comment]
See related PR: https://github.com/AdeonMaster/jsx-vanilla/pull/5
